Vocabulary_alt = {

    "21" : "Einundzwanzig",
    "672" : "sechshundertzweiundsiebzig",
    "A lot" : "Viel",
    "Actually" : "Eigentlich",
    "Add/Complete" : "Ergänzen",
    "Africa" : "Afrika",
    "Again" : "Wieder",
    "All right" : "Alles klar",
    "Alone" : "Allein",
    "Already" : "Schon",
    "Alright" : "In ordnung",
    "Also" : "Auch",
    "Always" : "Immer",
    "America" : "Amerika",
    "American" : "Amerikaner/in",        
    "Angry" : "Böse",
    "Annoy" : "Reizen",
    "Appeal" : "Gefallen",
    "April" : "April",
    "Arrange" : "Arrangieren",
    "Asia" : "Asien",
    "Ask" : "Fragen",
    "At" : "Zu",
    "August" : "August",
    "Australia" : "Australien",
    "Austria" : "Österreich",
    "Austrian" : "Österreicher/in",
    "Away" : "Weg",
    "Back (on the back)" : "Hinten",
    "Bad" : "Schlecht",
    "Be" : "Sein",
    "Beautiful" : "Schön",
    "Because" : "Denn",
    "Become" : "Werden",
    "Believe" : "Glauben",
    "Belong to" : "Gehören",
    "Big/tall" : "Groß",
    "Bite" : "Beißen",
    "Black" : "Schwarz",
    "Boring" : "Langweilig",
    "Both" : "Beide",
    "Bother" : "Stören",
    "Brasil" : "Brasilien",
    "Break" : "Brechen",
    "Breath" : "Atmen",
    "Bright" : "Hell",
    "Bring" : "Bringen",
    "Broken" : "Kaputt",
    "Brown" : "Braun",
    "Bulgaria" : "Bulgarien",
    "But" : "Aber",
    "Buy" : "Kaufen",
    "By bus" : "Mit dem bus",
    "Bye (telephone)" : "Auf wiederhören",
    "Calm" : "Ruhig",
    "Canada" : "Kanada",
    "Cancel" : "Stornieren",
    "Celebrate" : "Feiern",
    "Cheap" : "Billig",
    "Check, examine" : "Überprüfen",
    "China" : "China",
    "Choose" : "Wählen",
    "Clean (adj)" : "Sauber",
    "Clear (verb)" : "Klären",
    "Cloudy" : "Bewölkt",
    "Cold" : "Kalt",
    "Come" : "Kommen",
    "Comfortable" : "Bequem",
    "Cook (verb)" : "Kochen",
    "Cool" : "Kühl",
    "Correct" : "Richtig",
    "Cost (verb)" : "Kosten",
    "Create" : "Schaffen",
    "Cut (verb)" : "Schneiden",
    "Dance (verb)" : "Tanzen",
    "Dark" : "Dunkel",
    "Days of the week" : "Wochentage",
    "December" : "Dezember",
    "Decide/Determine" : "Entscheiden",
    "Deep" : "Tief",
    "Delicious" : "Lecker",
    "Denmark" : "Dänemark",
    "Destroy" : "Zerstören",
    "Die" : "Sterben",
    "Different" : "Verschieden",
    "Dirty" : "Schmutzig",
    "Discuss" : "Diskutieren",
    "Do" : "Tun",
    "Drive" : "Fahren",
    "Easy" : "Einfach",
    "Easy/light" : "Leicht",
    "Eat (for animals)" : "Fressen",
    "Eat (verb)" : "Essen",
    "Eight" : "Acht",
    "Eighteen" : "Achtzehn",
    "Eighty" : "Achtzig",
    "Elegant" : "Elegant",
    "Eleven" : "Elf",
    "Empty" : "Leer",
    "England" : "England",
    "English" : "Englisch",
    "Enough" : "Genug",
    "Equal" : "Gleich",
    "Every/everyone" : "Jede",
    "Everyone" : "Alle",
    "Everything" : "Alles",
    "Exactly" : "Genau",
    "Excited" : "Aufgeregt",
    "Exciting" : "Aufregend",
    "Excuse me (formal)" : "Entschuldigen Sie",
    "Excuse me (informal)" : "Entschuldigung",
    "Expect/await" : "Erwarten",
    "Expensive" : "Teuer",
    "Explain" : "Erklären",
    "Fall/Autumn" : "Fall",
    "False/Wrong" : "Falsch",
    "Fantastic" : "Fantastisch",
    "Far" : "Weit",
    "Fast" : "Schnell",
    "Fat" : "Dick",
    "February" : "Februar",
    "Feel" : "Empfinden",
    "Fetch" : "Holen",
    "Fifteen" : "Fünfzehn",
    "Fifty" : "Fünfzig",
    "Find" : "Finden",
    "First" : "Erste",
    "Fit (verb)" : "Passen",
    "Five" : "Fünf",
    "Fly" : "Fliegen",
    "Foggy" : "Neblig",
    "For" : "Für",
    "Forget" : "Vergessen",
    "Four" : "Vier",
    "Fourteen" : "Vierzehn",
    "Fourty" : "Vierzig",
    "France" : "Frankreich",
    "Free" : "Frei",
    "French" : "Französisch",
    "Fresh" : "Frisch",
    "From" : "Aus",
    "Funny" : "Lustig",
    "German" : "Deutsche/r",
    "Give" : "Geben",
    "Give (gift)" : "Schenken",
    "Go" : "Gehen",
    "Good" : "Gut",
    "Good day" : "Guten tag",
    "Good evening" : "Guten abend",
    "Good morning" : "Guten morgen",
    "Good night" : "Gute nacht",
    "Good-bye/See you again" : "Wiederschauen",
    "Good-bye (Informell)" : "Tschüss",
    "Good-bye (Formell)" : "Auf wiedersehen",
    "Gray" : "Grau",
    "Great" : "Toll",
    "Greece" : "Griechenland",
    "Green" : "Grün",
    "Grow" : "Wachsen",
    "Hang around" : "Hängen",
    "Happy" : "Glücklich",
    "Have" : "Haben",
    "Have to" : "Müssen",
    "He is" : "Er ist",
    "Healthy" : "Gesund",
    "Hear" : "Hören",
    "Heavy/difficult" : "Schwer",
    "Hello" : "Hallo",
    "Help (verb)" : "Helfen",
    "Here" : "Hier",
    "High" : "Hoch",
    "Horrify (verb)" : "Entsetzen",
    "Hot" : "Heiß",
    "How are you? (formal)" : "Wie geht es Ihnen?",
    "How are you? (informal)" : "Wie geht's dir?",
    "How many/much" : "Wie viel",
    "How old are you? (formal)" : "Wie alt sind Sie?",
    "Hundred" : "(ein)hundert",
    "I am" : "Ich bin",
    "I am okay" : "Mir geht's gut",
    "I am sorry" : "Es tut mir leid",
    "I beg your pardon" : "Wie bitte?",
    "I can't right now" : "Ich kann jetzt nicht",
    "I don't know" : "Ich weiß nicht",
    "I don't understand" : "Ich verstehe nicht",
    "I speak a bit of German" : "Ich spreche etwas Deutsch",
    "Imitate" : "Imitieren",
    "Immigrate" : "Immigrieren",
    "Important" : "Wichtag",
    "Interesting" : "Interessant",
    "Into" : "Ins",
    "Irak" : "Irak",
    "It is" : "Es ist",
    "Italy" : "Italien",
    "January" : "Januar",
    "Jog" : "Joggen",
    "July" : "Juli",
    "June" : "Juni",
    "Just a moment" : "Einen moment",
    "Know" : "Kennen",
    "Know (acquainted)" : "Wissen",
    "Late" : "Spät",
    "Lay/be Located (verb)" : "Liegen",
    "Learn" : "Lernen",
    "Leave" : "Verlassen",
    "Left" : "Links",
    "Lend" : "Leihen",
    "Like" : "Mögen",
    "Little (2)" : "Bisschen",
    "Live" : "Leben",
    "Long" : "Lang",
    "Look for" : "Suchen",
    "Lose" : "Verlieren",
    "Loud" : "Laut",
    "Love (verb)" : "Lieben",
    "Make" : "Machen",
    "March" : "März",
    "March (verb)" : "Marschieren",
    "May" : "Mai",
    "Maybe" : "Vielleicht",
    "Meet" : "Treffen",
    "Mexico" : "Mexiko",
    "Million" : "(ein)million",
    "Mr" : "Herr",
    "Name/Call" : "Nennen",
    "Need" : "Brauchen",
    "Nervous" : "Nervös",
    "Never" : "Nie",
    "New" : "Neu",
    "Next" : "Nächste",
    "Nice" : "Nett",
    "Nice to see you" : "Schön dich zu sehen",
    "Nine" : "Neun",
    "Nineteen" : "Neunzehn",
    "Ninety" : "Neunzig",
    "No idea" : "Keine ahnung",
    "No problem" : "Kein problem",
    "Nobody" : "Niemand",
    "North Amerika" : "Nordamerika",
    "November" : "November",
    "Now" : "Jetzt",
    "October" : "Oktober",
    "Of course" : "Natürlich",
    "Often" : "Oft",
    "Old" : "Alt",
    "Once again" : "Noch einmal",
    "One" : "Eins",
    "Only" : "Nur",
    "Open (adj)" : "Geöffnet",
    "Or" : "Oder",
    "Order (verb)" : "Bestellen",
    "Organize" : "Organisieren",
    "Over (there)" : "Drüben",
    "Paint" : "Malen",
    "Partner" : "Partner",    
    "Pay" : "Bezahlen",
    "Pay (verb)" : "Zahlen",
    
    #atras no deberia haber nouns
    
    "Perfect" : "Perfekt",
    
    
    "Photograph (verb)" : "Fotografieren",
    
    
    
    "Pilot" : "Pilot",
    "Pink" : "Rosa",
    "Pizza" : "Pizza",
    "Plane ticket" : "Flugticket",
    "Please" : "Bitte",
    "Please repeat (formal)" : "Bitte wiederholen Sie",
    "Poland" : "Polen",
    "Police officer" : "Polizist",
    "Polish" : "Polnisch",
    "Possible" : "Möglich",
    "Potato" : "Kartoffel",
    "Profession" : "Beruf",
    "Promise" : "Versprechen",
    "Protect" : "Schützen",
    "Put" : "Stellen",
    "Quiet" : "Leise",
    "Rain (noun)" : "Regen",
    "Reach" : "Reichen",
    "Read" : "Lesen",
    "Ready" : "Fertig",
    "Really" : "Wirklich",
    "Receive" : "Bekommen",
    "Recommend" : "Empfehlen",
    "Red" : "Rot",
    "Refrigerator" : "Kühlschrank",
    "Reside" : "Wohnen",
    "Restaurant" : "Restaurant",
    "Rice" : "Reis",
    "Rich" : "Reich",
    "Right" : "Rechts",
    "Right now" : "Gerade",
    "Ring" : "Ring",
    "River" : "Fluss",
    "Rome" : "Rom",
    "Room" : "Zimmer",
    "Roommate" : "Mitbewohner",
    "Round" : "Rund",
    "Run" : "Rennen",
    "Russia" : "Russland",
    "Russian" : "Russisch",
    "Sad" : "Traurig",
    "Sail (v)" : "Segeln",
    "Salad" : "Salat",
    "Salt" : "Salz",
    "Same (adj)" : "Gleich",
    "Sandwich" : "Butterbrot",
    "Saturday" : "Samstag",
    "Sausage" : "Wurst",
    "Say" : "Sagen",
    "Scarf" : "Schal",
    "Schedule" : "Fahrplan",
    "School" : "Schule",
    "Sea" : "Meer",
    "Secondary school" : "Gymnasium",
    "See" : "Sehen",
    "See you later" : "Bis später",
    "See you soon (Informal)" : "Bis bald",
    "Sell" : "Verkaufen",
    "Send (2nd verb)" : "Schicken",
    "Send (verb)" : "Senden",
    "September" : "September",
    "Seven" : "Sieben",
    "Seventeen" : "Siebzehn",
    "Seventy" : "Siebzig",
    "She is" : "Sie ist",
    "Shirt" : "Hemd",
    "Shoe" : "Schuh",
    "Short" : "Kurz",
    "Should, ought" : "Sollen",
    "Shout (verb)" : "Schreien",
    "Show (verb)" : "Zeigen",
    "Shower (verb)" : "Duschen",
    "Sick" : "Krank",
    "Sing" : "Singen",
    "Sister" : "Schwester",
    "Sit (v)" : "Sitzen",
    "Six" : "Sechs",
    "Sixteen" : "Sechzehn",
    "Sixty" : "Sechzig",
    "Size" : "Größe",
    "Skirt" : "Rock",
    "Sky" : "Himmel",
    "Sleep" : "Schlafen",
    "Slow" : "Langsam",
    "Small/little" : "Klein",
    "Smart" : "Klug",
    "Snail" : "Schnecke",
    "Snows (verb)" : "Schneien",
    "So long/Take care" : "Mach's gut",
    "So, thus, therefore" : "Also",
    "Soccer player" : "Fussballspieler",
    "Sofa" : "Sofa",
    "Some" : "Manche",
    "Someone" : "Jemand",
    "Something" : "Etwas",
    "Sometimes" : "Manchmal",
    "Son" : "Sohn",
    "Sort (verb)" : "Sortieren",
    "Soup" : "Suppe",
    "Spain" : "Spanien",
    "Speak" : "Sprechen",
    "Spider" : "Spinne",
    "Spring" : "Frühling",
    "Stain/mark" : "Fleck",
    "Stairway" : "Treppe",
    "Stand (verb)" : "Stehen",
    "Star" : "Stern",
    "Start (verb)" : "Beginnen",
    "Stay" : "Bleiben",
    "Steal" : "Stehlen",
    "Still" : "Noch",
    "Strawberry" : "Erdbeere",
    "Stressful" : "Stressig",
    "Stroll" : "Spazieren",
    "Strong" : "Stark",
    "Student" : "Schüler",
    "Study" : "Studieren",
    "Stylish" : "Schick",
    "Subway" : "U-Bahnstation",
    "Sugar" : "Zucker",
    "Summer" : "Sommer",
    "Sun" : "Sonne",
    "Sunday" : "Sonntag",
    "Sunscreen" : "Sonnencreme",
    "Surf" : "Surfen",
    "Sweatshirt" : "Sweatshirt",
    "Sweden" : "Schweden",
    "Swedish" : "Schwedisch",
    "Sweet" : "Süß",
    "Swim" : "Schwimmen",
    "Swimming pool" : "Schwimmbad",
    "Swiss" : "Schweizer/in",
    "Switzerland" : "die Schweiz",
    "Syria" : "Syrien",
    "T-shirt" : "T-shirt",
    "Table" : "Tisch",
    "Take" : "Nehmen",
    "Taxi stand" : "Taxistand",
    "Tea" : "Tee",
    "Teacher" : "Lehrer",
    "Team" : "Mannschaft",
    "Television" : "Fernseher",
    "Tell" : "Erzählen",
    "Ten" : "Zehn",
    "Thank you very much" : "Vielen dank",
    "Thanks" : "Danke",
    "Then" : "Dann",
    "There" : "Dort/Da",
    "They are" : "Sie sind",
    "Thief" : "Dieb",
    "Thing" : "Ding",
    "Think" : "Denken",
    "Thirst" : "Durst",
    "Thirteen" : "Dreizehn",
    "Thirty" : "Dreißig",
    "This" : "Diese",
    "Thousand" : "(ein)tausend",
    "Three" : "Drei",
    "Tickets" : "Fahrkarten",
    "Time" : "Zeit",
    "Tired" : "Müde",
    "To punch/kick" : "Stoßen",
    "Today" : "Heute",
    "Together" : "Zusammen",
    "Tomato" : "Tomate",
    "Tomorrow" : "Morgen",
    "Too bad" : "Schade",
    "Tooth" : "Zahn",
    "Train" : "Zug",
    "Train station" : "Bahnhof",
    "Travel" : "Reisen",
    "Tree" : "Baum",
    "Try/Taste" : "Probieren",
    "Turkey" : "Türkei",
    "Turkish" : "Türkisch",
    "Twelve" : "Zwölf",
    "Twenty" : "Zwanzig",
    "Two" : "Zwei",
    "Ugly" : "Hässlich",
    "Umbrella" : "Regenschirm",
    "Uncle" : "Onkel",
    "Understand" : "Verstehen",
    "Unfortunately" : "Leider",
    "University" : "Universität",
    "Until when?" : "Bis wann?",
    "Use (verb)" : "Benutzen",
    "Use, utilize" : "Verwenden",
    "Vacation" : "Urlaub",
    "Vase" : "Vase",
    "Vegetables" : "Gemüse",
    "Very" : "Sehr",
    "Vicinity" : "Nähe",
    "Video game" : "Videospiel",
    "Visit" : "Besuchen",
    "Wait" : "Warten",
    "Waiter" : "Kellner",
    "Walk" : "Laufen",
    "Want" : "Wollen",
    "Warm" : "Warm",
    "Warsaw" : "Warschau",
    "Wash" : "Waschen",
    "Watch" : "Schauen",
    "Water" : "Wasser",
    "We are" : "Wir sind",
    "Weak" : "Schwach",
    "Wear" : "Tragen",
    "Weather" : "Wetter",
    "Week" : "Wöche",
    "Weekend" : "Wochenende",
    "Welcome" : "Willkommen",
    "What is that?" : "Was ist das?",
    "What is your name? (formal)" : "Wie heißen Sie?",
    "When" : "Wann?",
    "Where" : "Wo?",
    "Where do you come from?(formal)?" : "Woher kommen Sie?",
    "Where from" : "Woher?",
    "Where going" : "Wohin?",
    "Where is?" : "Wo ist?",
    "Which" : "Welche?",
    "While" : "Während",
    "White" : "Weiß",
    "Who is that?" : "Wer ist das?",
    "Why" : "Warum?",
    "Wind" : "Wind",
    "Windows" : "Fenster",
    "Windy" : "Windig",
    "Wine" : "Wein",
    "Winter" : "Winter",
    "With" : "Mit",
    "Wonderful" : "Wunderbar",
    "Work (verb)" : "Arbeiten",
    "Write" : "Schreiben",
    "Year" : "Jahr",
    "Yellow" : "Gelb",
    "Yesterday" : "Gestern",
    "You're welcome" : "Gern geschehen",
    "You're welcome (2)" : "Bitte",
    "Young" : "Jung",
    "Zero" : "Null",
    "you are (formal, sing./plural)" : "Sie sind",
    "you are (informal, plural)" : "Ihr seid",
    "you are (informal, singular)" : "du bist",
}

Vocabulary_neu = {

    "Angry (2)" : "Sauer",
    "Rain (verb)" : "Regnen",
    "Possess" : "Besitzen",
    "Maintain/Receive (2)" : "Erhalten",
    "Recognize" : "Erkennen",
    "Describe" : "Beschreiben",
    "Serve" : "Dienen",
    "Follow" : "Folgen",
    "Impress" : "Imponieren",
    "Central America" : "Mittelamerika",
    "South America" : "Südamerika",
    "Great Britain" : "Großbritannien",
    "Ireland" : "Irland",
    "Netherlands" : "Die Niederlande",
    "Portugal" : "Portugal",
    "Romania" : "Rumänien",
    "Slovakia" : "Die Slowakei",
    "Czech Republic" : "Tschechien",
    "Careful" : "Vorsichtig",
    "Quit" : "Kündigen",
    "Burn" : "Brennen",
    "Cry" : "Weinen",
    "Solve" : "Lösen",
    "Be missing, lack" : "Fehlen",
    "Practice (verb)" : "Üben",
    "Chinese" : "Chinesisch",
    "Note (verb)" : "Notieren",
    "Whole/Complete" : "Ganz",
    "Meanwhile/Meantime" : "Mittlerweile",
    "Arrest/Detain" : "Verhaften",
    "Suddenly" : "Plötzlich",
    "Laugh (verb)" : "Lachen",
    "Terrible/Bad" : "Schlimm",
    "Dangerous" : "Gefährlich",
    "Quiet/Still" : "Still",
    "Outside" : "Draußen",
    "Feel (verb)" : "Fühlen",
    "Satisfied/Content" : "Zufrieden",
    "Are you okay?" : "Ist dir was passiert?",
    "Keep/Hold" : "Halten",
    "Firm/Fixed" : "Fest",
    "I don't care" : "Mir ist das egal",
    "Because of/On account of" : "Wegen",
    "Speak/Talk" : "Reden",
    "Annoy/Bother" : "Nerven",
    "All the same" : "Egal",
    "Let/Allow" : "Lassen",
    "Bully/Harass (verb)" : "Mobben",
    "Threaten" : "Bedrohen",
    "Hurt/Wound" : "Verletzen",
    "Fury/Rage" : "Die Wut",
    "Forest/Wood" : "Der Wald",
    "Surprise (verb)" : "Überraschen",
    "Tempo/Pace" : "Das Tempo",
    "Remember/Remind" : "Erinnern",
    "Hug/Embrace" : "Umarmen",

}

Vocabulary_nommen = {

    "A few/a couple of" : "Das Paar,-e",
    "ATM" : "Der Geldautomat,-en",
    "Actor" : "Der Schauspieler,-",
    "Admission ticket" : "Die Eintrittskarte,-n",
    "Adress" : "Die Adresse,-n",
    "Afternoon" : "Der Nachmittag,-e",
    "Age" : "Das Alter,-",
    "Air" : "Die Luft,Lüfte",
    "Airplane" : "Das Flugzeug,-e",
    "Airport" : "Der Flughafen,Flughäfen",
    "Animal" : "Das Tier,-e",
    "Announcement" : "Die Ansage,-n",
    "Answering machine" : "Der Anrufbeantworter,-",
    "Apartment" : "Die Wohnung,-en",
    "Arm" : "Der Arm,-e",
    "Arrival" : "Die Ankunft,Anküfte",
    "Art Museum" : "Die Kunsthalle,-n",
    "Artist" : "Der Künstler,-",
    "Aunt" : "Die Tante,-n",
    "Baby" : "Das Baby,-s",
    "Bag (feminine)" : "Die Tasche,-n",
    "Bag (plastic)" : "Die Tüte,-n",
    "Bakery" : "Die Bäckerei,-en",
    "Ballpoint pen" : "Der Kuli,-s",
    "Banana" : "Die Banane,-n",
    "Basket" : "Der Korb,Körbe",
    "Bathroom" : "Das Badezimmer,-",
    "Bear" : "Der Bär,-en",

    "Beard" : "Der Bart",
    "Beauty" : "Die Schönheit",
    "Bed" : "Das Bett",
    "Bedroom" : "Das Schlafzimmer",
    "Bee" : "Die Biene",
    "Beer" : "Das Bier",
    "Beetle" : "Der Käfer",
    "Beginning" : "Der Anfang",
    "Bicycle" : "Das Fahrrad",
    "Bird" : "Der Vogel",
    "Birthday" : "Der Geburtstag",
    "Blouse" : "Die Bluse",
    "Bookcase" : "Das Bücherregal",
    "Bottle" : "Die Flasche",
    "Bowl" : "Die Schale",
    "Boy" : "Der Junge",
    "Bread" : "Das Brot",
    "Breakfast" : "Das Frühstück",
    "Brightness" : "Die Helligkeit",
    "Brother" : "Der Bruder",
    "Butcher" : "Der Metzger",
    "Button (clothes)" : "Der Knopf",
    "Call" : "Der Anruf",
    "Car" : "Der Wagen",
    "Carpet" : "Der Teppich",
    "Cash register" : "Die Kasse",
    "Cat" : "Die Katze",
    "Cellphone" : "Das Handy",
    "Chair" : "Der Stuhl",
    "Chancellor" : "Der Kanzler",
    "Check" : "Die Rechnung",
    "Cheers" : "Das Prost",
    "Cheese" : "Der Käse",
    "Chess" : "Das Schach",
    "Chicken" : "Das Hähnchen",
    "Child" : "Das Kind",
    "Chocolate" : "Die Schokolade",
    "Cinema" : "Das Kino",
    "City" : "Die Stadt",
    "Class/Course" : "Der Kurs",
    "Clock" : "Die Uhr",
    "Closet" : "Der Schrank",
    "Clothes" : "Die Kleidung",
    "Cloud" : "Die Wolke",
    "Clown" : "Der Clown",
    "Coat" : "Der Mantel",
    "Coffee" : "Der Kaffee",
    "Computer" : "Der Computer",
    "Concert" : "Das Konzert",
    "Corner" : "Die Ecke",
    "Cosmetics" : "Die Kosmetiks",
    "Cost" : "Die Kosten",
    "Couch" : "Die Couch",
    "Cow" : "Die Kuh",
    "Credit card" : "Die Kreditkarte",
    "Cup" : "Die Tasse",
    "Dance (noun)" : "Der Tanz",
    "Danger, Caution" : "Die Achtung",
    "Date" : "Das Date",
    "Daughter" : "Die Tochter",
    "Dentist" : "Der Zahnarzt",
    "Department store" : "Das Kaufhaus",
    "Departure" : "Die Abfahrt",
    "Desk" : "Der Schreibtisch",
    "Dictionary" : "Das Wörterbuch",
    "Dinner" : "Das Abendessen",
    "Doctor" : "Der Arzt",
    "Dog" : "Der Hund",
    "Door" : "Die Tür",
    "Dress" : "Das Kleid",
    "Duck" : "Die Ente",
    "Earth" : "Die Erde",
    "Egg" : "Das Ei",
    "Elephant" : "Der Elefant",
    "Elevator" : "Der Aufzug",
    "Exam" : "Das Examen",
    "Fall/Autumn (2)" : "Der Herbst",
    "Family" : "Die Familie",
    "Father" : "Der Vater",
    "Fear" : "Die Angst",
    "Feather" : "Die Feder",
    "Fire" : "Das Feuer",
    "Fish" : "Der Fisch",
    "Floor" : "Der Boden",
    "Flower" : "Die Blume",
    "Food" : "Das Essen",
    "Food/Dish" : "Die Speise",
    "Football game" : "Das Fußballspiel",
    "Foreigner" : "Der Ausländer",
    "French fries" : "Die Pommes",
    "Friend" : "Der Freund",
    "Friend/Girlfriend" : "Die Freundin",
    "Fruit" : "Das Obst",
    "Fun" : "Der Spaß",
    "Furniture" : "Das Möbel",
    "Game" : "Das Spiel",
    "Gender" : "Das Geschlecht",
    "Gift" : "Das Geschenk",
    "Girl" : "Das Mädchen",
    "Glass" : "Das Glas",
    "Government" : "Die Regierung",
    "Grandfather" : "Der Großvater",
    "Grandmother" : "Die Großmutter",
    "Greeting" : "Der Gruß",
    "Guest" : "Der Gest",
    "Guitar" : "Die Gitarre",
    "Hair" : "Das Haar",
    "Hand" : "Die Hand",
    "Hat" : "Der Hut",
    "Hell" : "Die Hölle",
    "Help (noun)" : "Die Hilfe",
    "Hike (noun)" : "Die Wanderung",
    "Horse" : "Das Pferd",
    "Hour" : "Die Stunde",
    "House" : "Das Haus",
    "Hunger" : "Der Hunger",
    "Husband" : "Der Ehemann",
    "Ice-cream" : "Das Eis",
    "Idea" : "Die Idee",
    "Idea (2)" : "Die Ahnung",
    "Insect" : "Das Insekt",
    "Instruction, teaching" : "Der Unterricht",
    "Invitation" : "Die Einladung",
    "Jacket" : "Die Jacke",
    "Jewelry" : "Der Schmuck",
    "Job interview" : "Das Jobinterview",
    "Key" : "Der Schlüssel",
    "King" : "Der König",
    "Kitchen" : "Die Küche",
    "Lady" : "Die Dame",
    "Lake" : "Der See",
    "Lamp" : "Die Lampe",
    "Language" : "Die Sprache",
    "Lawyer" : "Der Anwalt",
    "Lesson" : "Die Lektion",
    "Letter" : "Der Brief",
    "Letter (of a word)" : "Der Buchstabe",
    "Library" : "Die Bibliothek",
    "Magazine" : "Die Zeitschrift",
    "Man" : "Der Mann",
    "Market" : "Der Markt",
    "Meat" : "Das Fleisch",
    "Mechanic" : "Der Mechaniker,-",
    "Menu" : "Die Speisekarte,-n",
    "Mineral water" : "Das Mineralwasser,-",
    "Minute" : "Die Minute",
    "Mirror" : "Der Spiegel,-",
    "Miss" : "Die Frau,-en",
    "Monday" : "Der Montag,-e",
    "Money" : "Das Geld,-er",
    "Moon" : "Der Mond,-e",
    "Mother" : "Die Mutter,Mütter",
    "Mountain" : "Der Berg,-e",
    "Mouse" : "Die Maus,Mäuse",
    "Movie" : "Der Film,-e",
    "Nature" : "Die Natur,-en",
    "Newspaper" : "Die Zeitung,-en",
    "Noodle/pasta" : "Die Nudel,-n",
    "Notebook" : "Das Heft,-e",
    "Number" : "Die Zahl",
    "Nurse" : "Die Krankenschwester,-n",
    "Offer" : "Das Angebot",
    "Oil" : "Das Öl,-e",
    "Orange (fruit)" : "Die Orange,-n",
    "Oven" : "Der Ofen,Öfen",
    "Owl" : "Die Eule,-n",
    "Pants" : "Die Hose,-n",
    "Parent" : "Das Elter,-n",
    "Park" : "Der Park,-s",
    "Parrot" : "Der Papagei,-en",
    "Participant (masculine)" : "Der Teilnehmer",
    "Party" : "Die Party,-s",
    "Passport" : "Der Pass,Pässe",
    "Path" : "Der Weg",
    "Pen" : "Der Stift,-e",
    "Pencil" : "Der Bleistift,-e",
    "People" : "Die Leute",
    "Pet" : "Das Haustier,-e",
    "Pharmacy" : "Die Apotheke,-n",
    "Piano" : "Das Klavier,-e",
    "Picture" : "Das Bild,-er",
    "Pig" : "Das Schwein,-e",
    "Pillow" : "Das Kissen",
    "Plant" : "Die Pflanze",
    "Pronunciation" : "Die Aussprache",
    "Queen" : "Die Königin",
    "Registration, enrollment" : "Die Anmeldung",
    "Reservation" : "Die Reservierung",
    "Result" : "Das Ergebnis",
    "Sea/Ocean" : "Die See",
    "Seat" : "Der Sitz",
    "Sender" : "Der Absender",
    "Sibling" : "Das Geschwister",
    "Story" : "Die Geschichte",
    "Street number" : "Die Hausnummer",
    "Suit jacket" : "Das Sakko",
    "Toilet" : "Die Toilette",
    "Track (train)" : "Das Gleis",
    "Travel center" : "Das Reisezentrum",
    "Tuesday" : "Der Dienstag",
    "Vegetarian" : "Der Vegetarier",
    "Violine" : "Die Geige",
    "Wall" : "Die Wand",
    "Wednesday" : "Der Mittwoch",




}

Vocabulary_neue_nommen = {

    #alte nommen


    #neue nommen! 
    "Beach" : "Der Strand,Strände",
    "Suitcase/Bag" : "Der Koffer,-",
    "South" : "Der Süden",
    "North" : "Der Norden",
    "West" : "Der Westen",
    "East" : "Der Osten",
    "Radio" : "Das Radio,-s",
    "Accident" : "Der Unfall, Unfälle",
    "Antartica" : "Die Antarktis,-",
    "Earth" : "Die Erde, -n",
    "Continent" : "Der Erdteil, -e",
    "Surfboard" : "Das Surfbrett, -er",
    "Desire/Lust" : "Die Lust",
    "Danger/Risk" : "Die Gefahr",
    "Mood" : "Die Laune",
    "Conclusion/End" : "Der Schluss",
    "Exhibition/Display" : "Die Ausstellung",
    "Coward/Chicken" : "Der Feigling",
    "Answer/Communication" : "Der Bescheid",
    "Nonsense" : "Der Schmarren",
    "Peace" : "Der Frieden",
    "Pain/Ache" : "Das Weh",
    "Error/Fault" : "Der Fehler",
    "Song" : "Das Lied",
    "Devil/Demon" : "Der Taufel",
    "Exam (2)" : "Die Prüfung",
    







}

Vocabulary_trennbare_verben = {

    "Agree (with)" : "Zustimmen",
    "Approach/Collide" : "Anfahren",
    "Arrive" : "Ankommen",
    "Ascribe/Attribute" : "Zuschreiben",
    "Begin (verb)" : "Anfangen",
    "Cancel/Call of" : "Absagen",
    "Carry out/Execute" : "Ausführen",
    "Cease/End" : "Aufhören",
    "Change clothes" : "Umziehen",
    "Choose" : "Auswählen",
    "Choose/Select" : "Aussuchen",
    "Clean up/ tidy up" : "Aufräumen",  
    "Clean/ tidy up (2)" : "Saubermachen",     
    "Close (verb)" : "Zumachen",
    "Concern, tackle, approach" : "Angehen", 
    "Come back" : "Wiederkommen",
    "Complete/Finish" : "Fertigmachen",
    "Depart" : "Abfahren",
    "Depart/Leave" : "Weggehen",
    "Drive in/Enter" : "Reinfahren",
    "Excite" : "Aufregen",
    "Enter/Input" : "Eingeben",
    "Fall asleep" : "Einschlafen",
    "Get on (transportation)" : "Einsteigen",
    "Get there/Manage" : "Hinkommen",        
    "Go along" : "Mitgehen",
    "Go in/Enter" : "Reingehen",
    "Hand over, deliver" : "Abgeben",        
    "Introduce" : "Vorstellen",
    "Invite" : "Einladen",
    "Keep hold of" : "Festhalten",
    "Lean against" : "Anlehnen",
    "Leave" : "Losgehen",
    "Look around" : "Umschauen",
    "Look at, watch" : "Ansehen",
    "Look like" : "Aussehen",
    "Make a date" : "Verabreden",
    "Move" : "Umziehen",
    "Offer/ Propose" : "Anbieten",
    "Open (verb)" : "Aufmachen",
    "Participate" : "Mitmachen",
    "Pay attention/Watch out" : "Aufpassen",
    "Pick up/ Collect" : "Abholen",
    "Prepare" : "Vorbereiten",
    "Pronounce" : "Aussprechen",
    "Put down/assign" : "Abstellen",
    "Register/Enroll" : "Anmelden",
    "Relax" : "Ausruhen",
    "Spend" : "Ausgeben",
    "Stand/get up" : "Aufstehen",
    "Switch on/Intervene" : "Einschalten",
    "Take along" : "Mitnehmen",
    "Take away" : "Wegnehmen",
    "Telephone (verb)" : "Anrufen",
    "Throw away" : "Wegwerfen",
    "Tick, cross" : "Ankreuzen",
    "Transfer (to other transportation)" : "Umsteigen",
    "Turn off" : "Ausmachen",
    "Turn on" : "Anmachen",
    "Wake up" : "Aufwachen",
    "Walking" : "Spazierengehen",
    "Write down" : "Aufschreiben",


}

Vocabulary_Kapitel_10 = {

     #Sequenz 1: Kontakte pflegen
    "Average" : "Der Durchschnitt",
    "Hour" : "Die Stunde,-n",
    "Web" : "Das Netz",
    "Use (verb)" : "Nutzen",
    "Surf (internet)" : "Surfen",
    "Smartphone" : "Das Smartphone,-s",
    "Communication" : "Die Kommunikation",
    "Information" : "Die Information,-en",
    "So, thus" : "Also",
    "Chat (verb)" : "Chatten",
    "Telephone (verb)" : "Telefonieren",
    "For example" : "Zum Beispiel",
    "Search engine" : "Die Suchmaschine,-n",
    "Simply" : "Einfach",
    "Blog" : "Der Blog,-s",
    "Video" : "Das Video,-s",
    "Social" : "Sozial",
    "Network" : "Das Netzwerk,-e",
    "Particularly, especially" : "Besonders",
    "Young" : "Jung",
    "Second (about time)" : "Die Sekunde,-n",
    "Since" : "Seit",
    "Call (noun)" : "Der Anruf,-e",
    "Connection" : "Die Verbindung,-en",
    "Finished" : "Beendet",
    "Begin" : "Beginnen",
    "Duration" : "Die Dauer",
    "Telephone" : "Das Telefon,-e",
    "Login" : "Der Login,-s",
    "Register" : "Registrieren",
    "Registration" : "Die Registrierung,-en",
    "Possible" : "Möglich",
    "Pasta" : "Die Pasta",
    "Recipe" : "Das Rezept,-e",
    "Fresh" : "Frisch",
    "Nothing" : "Nichts",
    "Wine cellar" : "Der Weinkeller",
    "Reader" : "Der Leser",
    "Zucchini" : "Der Zucchini,-s",
    "Ingredient" : "Die Zutat,-en",
    "Statement" : "Die Aussage,-n",
    "Tip" : "Der Tipp,-s",
    "Cooking pasta (noun)" : "Das Pastakochen",
    "Party (2)" : "Das Fest,-e",
    "Chatting" : "Das Chatten",
    "Path" : "Der Weg,-e",
    "E-mail" : "Die E-mail,-s",
    "Programmer (masc/fem)" : "Der Programmierer/in",
    "Send (2)" : "Verschicken",
    "Making phone calls" : "Das Telefonieren",
    "Following/subsequent" : "Folgend(e)",
    "Program" : "Das Programm,-e",
    "App" : "Die App,-s",
    
    #Sequenz 2: Freunde und Nachbarn
    "Oh well" : "Na ja",
    "Manage, achieve, accomplish" : "Schaffen",
    "Help (noun)" : "Die Hilfe,-n",
    "Offer (verb)" : "An|bieten",
    "Refuse/decline" : "Ab|lehnen",
    "Carry/take" : "Tragen",
    "New Year's Eve party" : "Die Silvesterparty,-s",
    "Sparkling wine" : "Der Sekt",
    "Enough" : "Genug",
    "Firework" : "Das Feuerwerk,-e",
    "Dialogue" : "Der Dialog,-e",
    "Know each other" : "Sich kennen",
    "Happy new year" : "Gutes neues Jahr",
    "New year's eve" : "Das Silvester",
    "Happy new year (2)" : "Frohes neues Jahr",
    "Birthday cake" : "Der Geburtstagskuchen",
    "As far as/So far" : "Soweit",
    "Whether/if" : "Ob",
    "Marry" : "Heiraten",
    "Wedding" : "Die Trauung,-en",
    "Take place" : "Statt|finden",
    "Wedding (2)" : "Die Hochzeit,-en",
    "The Christmas dinner" : "Das Weihnachtessen",
    "Forget" : "Vergessen",
    "Congratulations" : "Glückwunsch,-e",
    "Christmas" : "Das Weihnachten",
    "Merry Christmas" : "Frohe Weihnachten",

    #Sequenz 3: Treffpunkte
    "Swimming pool" : "Das Schwimmbad,Schwimmbäder",
    "Playing guitar" : "Gitarre spielen",
    "Come back" : "Wieder|kommen",
    "Funny" : "Lustig",
    "Recommend" : "Empfehlen",
    "International" : "International",
    "Product" : "Das Produkt,-e",
    "Positive" : "Positiv",
    "Negative" : "Negativ",
    "Enthusiastic" : "Begeistert",
    "Summer night" : "Die Sommernacht,Sommernächte",
    "Cooking (noun)" : "Das Kochen",
    "Theater workshop" : "Der Theater-Workshop,-s",
    "Music arena" : "Die Musik-Arena",
    "Later" : "Später",
    "Beginning of a word" : "Der Wortanfang,Wortanfänge",
    "Ending of a word" : "Das Wortende,-n",
    "Art" : "Die Kunst,Künste",
    "Syllable" : "Die Silbe,-n",
    "Pronounce" : "Aussprechen",

    # 15 März
    "Above" : "Über",
    "Answer (verb, direct person)" : "Beantworten",
    "Certain, safe, sure" : "Sicher",
    "Colleague (masc)" : "Der Kollege,-n",
    "Congratulate" : "Gratulieren",
    "Divorced" : "Geschieden",
    "Download (verb)" : "herunter|laden",
    "File" : "Die Datei",
    "Folder" : "Der Ordner,-s",
    "Married" : "Verheiratet",
    "Origin" : "Die Herkunft",
    "Other (adj)" : "Andere",
    "Person" : "Die Person,-en",
    "Place of residence" : "Der Wohnort",
    "Post (verb)" : "Posten",
    "Send" : "Senden",
    "Send (for peopl/things)" : "Verschicken",
    "Shopping (verb)" : "Ein|kaufen",
    "Single/Unmarried" : "Ledig",
    "Thing (2)" : "Die Sache,-n",
    "Upload (verb)" : "Hoch|laden",
    "Use (noun)" : "Die Nutzung",
    "User" : "Der User",
    "User (2)" : "Der Nutzer",

    # 22 März
    "Contribution" : "Der Beitrag",
    "Pedestrian (male)" : "Der Fußgänger",
    "Task" : "Die Aufgabe",
    "Discover" : "Entdecken",
    "Little/few" : "Wenig",
    "Exercise (noun)" : "Die Übung",
    "Correct (2)" : "Korrekt",
    "Motivation" : "Die Motivation",
    "Success" : "Der Erfolg",
    "Interview" : "Das Interview",
    "Argentina" : "Argentinien",
    "Map" : "Der Stadtplan",
    "Castle (Residency)" : "Das Schloss",
    "Castle (Military)" : "Der Burg",
    "Church" : "Die Kirche",
    "Bridge" : "Die Brücke",
    "Stroller" : "Der Kinderwagen",
    "At least" : "Mindestens",
    "Mostly/largely" : "Meistens",
    "Wish (verb)" : "Wünschen",
    "Terrible" : "Schrecklich",
    "Difficult" : "Schwierig",
    "Enthusiastic" : "Begeistert",
    
}
    
Vocabulary_Kapitel_11 = {

    #Sequenz 1: Besuch in Heidelberg
    "City tour" : "Die Stadtrundfahrt,-en",
    "Castle" : "Das Schloss,Schlösser",
    "City map" : "Der Stadtplan,Stadtpläne",
    "Ask/Request" : "bitten",
    "React" : "Reagieren",
    "Departure time" : "Die Abfahrtszeit,-en",
    "May/Can/Be allowed to" : "Dürfen",
    "University museum" : "Das Universitätmuseum,Universitätmuseen",
    "Around the corner" : "Um die Ecke",
    "Something" : "Was(etwas)",
    "Us" : "Uns(wir)",
    "Father" : "Der Vater,Väter",
    "Give/Present" : "Schenken",
    "Him" : "Ihm",
    "Stroller" : "Der Kinderwagen,Kinderwägen",
    "Heavy" : "Schwer",
    "Thank (verb)" : "Danken",
    "Plan/Map" : "Der Plan,Pläne",
    "Immediately" : "Sofort",
    "Admission price" : "Der Eintrittspreis,-e",
    "Including/Inclusive" : "Inklusive",
    "Adult" : "Der/Die Erwachsene,-n",
    "Person with discount" : "Der/Die Ermäßigte,-n",
    "Guidance/Lead" : "Die Führung,-en",
    "Group" : "Die Gruppe,-n",
    "Student" : "Der Schüler,-",
    "Student feminine" : "Die Schülerin,-nen",
    "Senior citizen" : "Der Senior,-en",
    "Korean" : "Koreanisch",
    "Japanese" : "Japanisch",
    "Bank" : "Die Bank,-en",
    "Money" : "Das Geld",
    "ATM" : "Der Geldautomat",
    "Mail post" : "Die Post",
    "Museum shop" : "Der Museumsshop",
    "Postcard" : "Die Postkarte,-n",
    "Souvenir" : "Das Souvenir,-s",
    "Brochure" : "Der Prospekt,-e",
    "City centre" : "Das Stadtzentrum",
    "You're welcome" : "Bitte sehr",
    "Abroad/Foreign countries" : "Das Ausland",
    "Norway" : "Norwegen",
    "Canada" : "Kanada",
    "Send (3)" : "Schicken",
    "Topic" : "Das Thema,Themen",
    "Shopping (noun)" : "Das Einkaufen",
    "Travelling (noun)" : "Das Reisen",
    "Train ticket" : "Das Zugticket,-s",
    "Bus timetable" : "Der Busfahrplan,Busfahrpläne",

    #Sequenz 2: Ich bin leider zu spät
    "Time indication" : "Die Zeitangabe,-n",
    "Delay" : "Die Verspätung,-en",
    "Hospital" : "Das Hospital,-e",
    "Need (verb)" : "Brauchen",
    "Punctual" : "Pünktlich",
    "Engineer (male)" : "Der Ingenieur,-e",
    "Engineer (female)" : "Die ingenieurin,-nen",
    "Photographer (male)" : "Der Fotograf,-en",
    "Photographer (female)" : "Die Fotografin,-nen",
    "Photo studio" : "Das Fotostudio,-s",
    "Center" : "Das Zentrum,Zentren",
    "Normally" : "Normalerweise",
    "Sometimes" : "Manchmal",
    "Traffic jam" : "Der Stau,-s",
    "Chemistry" : "Die Chemie",
    "Tram" : "Die Straßenbahn,-en",
    "On foot" : "zu Fuß (gehen)",
    "Stand" : "Stehen",
    "Something (2)" : "Etwas",
    "Mark/Time" : "Das Mal",
    "Breakdown/Malfunction" : "Die Panne,-n",
    "Portugal" : "Portugal",
    "Punctuality/Accuracy" : "Die Pünktlichkeit",
    "Official/Officially" : "Offiziell",
    "One/People" : "Man",
    "Funny/Strange" : "Komisch",
    "Unpunctual" : "Unpünktlich",
    "Homeland, Native country" : "Das Heimatland,Heimatländer",

    #Sequenz 3: Wie geht das?
    "Print" : "Drucken",
    "Scanner" : "Der Scanner",
    "Scan" : "Scannen",
    "Copy (verb)" : "Kopieren",
    "Copy (noun)" : "Die Kopie,-n",
    "Download (noun)" : "Der Download,-s",
    "Download (verb)" : "Downloaden",
    "Download (verb,2)" : "Herunter|laden",
    "Button" : "Der Button,-s",
    "Press" : "Drücken",
    "Click (verb)" : "Klicken",
    "Paper" : "Das Papier,-e",
    "Explain" : "Erklären",
    "Copy (verb noun)" : "Das Kopieren",
    "Choose" : "Wählen",
    "Color copy" : "Die Farbkopie,-n",
    "Number/Quantity" : "Die Anzahl,-en",
    "Enter/Input" : "Ein|geben",
    "Album" : "Das Album,Alben",

    #Übungen
    "Office" : "Das Büro",
    "Bike/Wheel" : "Das Rad",
    "Appointment" : "Der Termin",
    "Polite" : "Höflich",
    "Boss" : "Der Chef",
    "Color" : "Die Farbe",
    "ID" : "Der Ausweis",
    "Copier" : "Der Kopierer",
    "Click (noun)" : "Der Klick",
    "Click (verb)" : "An|klicken",
    "Press a button" : "Einen Button drücken",
    "How does that work?" : "Wie geht das denn?",
    "Instruction" : "Die Anleitung",
    "Create" : "Erstellen",
    "Admission" : "Der Eintritt",
    "Practice/Excercise (verb)" : "Üben",

    #29 März
    "Cheerful/lively" : "Munter",
    "Motivated" : "Motiviert",
    "Satisfied/content" : "Zufrieden",
    "Cough" : "Der Husten",
    "Fever" : "Das Fieber",
    "Have breafkast (verb)" : "Frühstücken",
    "Early/initial" : "Früh",
    "Touristic" : "Touristische",
    "Attraction" : "Die Attraktion,-en",
    "Vineyard" : "Der Weinberg",
    "Tower" : "Der Turm",
    "Holy Spirit Church" : "Die Heiliggeistkirche",
    "View (verb)" : "Besichtigen",
    "Excursion" : "Der Ausflug",
    "Bicycle tour" : "Die Fahrradtour",
    "Pub/Bar" : "Die Kneipe",
    "Glasses" : "Die Brille",

}

Vocabulary_Kapitel_12 = {
 
    #Sequenz 1: Das Praktikum
    "Agency/Bureau" : "Die Agentur,-en",
    "Commitment/Promise/Acceptance" : "Die Zusage",
    "Internship" : "Das Praktikum",
    "Dear Mrs" : "Sehr geehrte Frau",
    "Dear Mr" : "Sehr geehrter Herr",
    "Application/Job application" : "Die Bewerbung,-en",
    "Telephone conversation/Phone call" : "Das Telefongespräch,-e",
    "Workday" : "Der Arbeitstag,-e",
    "Greet/Welcome (verb)" : "Begrüßen",
    "Secretariat" : "Das Sekretariat,-e",
    "Personnel Agency" : "Die Personalagentur,-en",
    "Inform (verb)" : "Informieren",
    "Lead/Conduct" : "Leiten",
    "Intern (male)" : "Der Praktikant,-en",
    "Intern (female)" : "Die Praktikantin,-nen",
    "Marketing" : "Das Marketing",
    "Be here" : "Da sein",
    "Oh" : "Oh weh",
    "Chaos" : "Das Chaos",
    "Eye" : "Das Auge,-n",
    "Only" : "Nur",
    "Applicant/Candidat (male)" : "Der Bewerber",
    "Applicant/Candidat (female)" : "Die Bewerberin,-nen",
    "Fast (2)" : "Fix",
    "Otherwise/Else" : "Sonst",
    "Angry (2)" : "Sauer",
    "Wall" : "Die Wand",
    "Desk" : "Der Schreibtisch",
    "Business card" : "Die Visitenkarte",
    "Plant" : "Die Pflanze,-n",
    "Poster" : "Das Plakat",
    "Calendar" : "Der Kalendar",
    "Room/Space" : "Der Raum,Räume",
    "Start (Verb,2)" : "Starten",
    "Print" : "Aus|drucken",
    "Discussion/Meeting" : "Die Besprechung",
    "Mean, to mean (verb)" : "Heißen",
    "Mean (verb,2)" : "Bedeuten",

    #Sequenz 2: Neuer Job, neue Stadt
    "To" : "An",
    "Inbox/Incoming mail" : "Der Posteingang,Posteingänge",
    "Sending (noun)" : "Das Senden",
    "Rubbish bin" : "Der Papierkorb,Papierkörbe",
    "Job" : "Der Job,-s",
    "Whole/Complete" : "Ganz",
    "Different/Distinct" : "Anders",
    "When/Than/As" : "Als",
    "Studies/Study" : "Das Studium,Studien",
    "Canteen/Cafeteria" : "Die Kantine,-n",
    "Coffee machine" : "Die Kaffeemaschine,-n",
    "Speak/talk" : "Reden",
    "Room number" : "Die Zimmernummer,-n",
    "At midday" : "Zu Mittag",
    "Ground meat" : "Das Hackfleisch",
    "First/At first/Firstly" : "Zuerst",
    "Concept/Idea" : "Das Konzept",
    "Website" : "Die Internetseite,-n",
    "Content" : "Der Inhalt",
    "Side/Page" : "Die seite,-n",
    "Schedule/Time plan" : "Der Zeitplan,Zeitpläne",
    "Agenda" : "Die Agenda,Agenden",
    "Discussion/Argument" : "Die Diskussion,-en",

    #Übungen
    "Promise/agree (verb)" : "Zu|sagen",
    "Ballpoint pen" : "Der Kugelschreiber",
    "Sound (verb)" : "Klingen",
    "Sound (noun)" : "Der Klang",
    "Great/Awesome" : "Klasse",
    "First/At first" : "Zuerst",
    "Together (2)" : "Gemeinsam",
    "Content/Substance" : "Der Inhalt",
    "Schedule (2)" : "Der Zeitplan",
    "Conversation/Dialogue" : "Das Gespräch",
    "Choose (2)" : "Aus|wählen",
    "Clean (2)" : "Putzen",
    "Enjoy" : "Genießen",
    "Folder (2)" : "Die Mappe",
    "Dishes" : "Das Geschirr",
    "Wash (toilette,dishes, etc.)" : "Spülen",
    "Consider/Observe" : "Beachten",
    "Conversation" : "Das Gespräch",
    "Customer" : "Der Kunde/in",
    "Polite" : "Höflich",
    "Insert/Stick" : "Stecken",
    "Absolutely" : "Unbedingt",

    #05 April
    "Screen" : "Der Bildschirm",
    "Ballpoint pen" : "Der Kugelschreiber",
    "Leaf/Sheet" : "Das Blatt",
    "Glasses" : "Die Brille",
    "Mouse" : "Die Maus",
    "Keyboard" : "Die Tastatur",
    "Probably" : "Wohl",
    "Describe" : "Be|schreiben",
    "Box (noun)" : "Die Kiste",
    "Miss (verb)" : "Verpassen",

    #12 April
    "Clean/Tidy up" : "Sauber|machen",
    "Exam" : "Die Prüfung,-en",
    "Bake" : "Backen",
    "Stove" : "Der Herd",
    "Cake" : "Der Kuchen",
    "Kitchen" : "Die Küche",
    "Hard" : "Hart",
    "Number (verb)" : "Nummerieren",
    "Take out" : "Ausführen",
    "Food (for animals)" : "Das Futter",
    "Previous" : "Vorherig",
    "Prohibition/Ban" : "Das Verbot",
    "Permission/Authorization" : "Die Erlaubnis",
    "Cruise ship" : "Das Kreuzfahrtschiff",
    "Box (verb)" : "Boxen",
    "Ping-pong" : "Das Tischtennis",
    "Necklace" : "Die Kette",
    "Smoke (verb)" : "Rauchen",
    "Put down/Assign" : "Ab|stellen",
    "Parcel/Plot" : "Das Grundstück",
    "Surfboard" : "Das Surfbrett",
    "Skate (verb)" : "Skaten",
    "Announce by poster/Put up posters" : "Plakatieren",
    "Shop/Store" : "Der Laden",
    "Business/Enterprise" : "Das Geschäft",
    "Count (verb)" : "Zählen",

}

Vocabulary_Kapitel_13 = {

    #Übungen
    "Grandson" : "Der Enkel",
    "Granddaughter" : "Die Enkelin",
    "Grandchild" : "Das Enkelkind",
    "Separate" : "Trennen",
    "Mother (2)" : "Die Mama",
    "Father (2)" : "Der Papa",
    "Family tree" : "Der Stammbaum",
    "Excellent/Super" : "Prima",
    "Village/Town" : "Das Dorf",
    "Experience (2)" : "Erfahren",
    "Washing machine/Clothes washer" : "Die Waschmaschine",
    "Load the dishwasher" : "Die Spülmaschine einräumen",
    "Unload the dishwasher" : "Die Spülmaschine ausräumen",
    "Turn on the washing machine" : "Die Waschmaschine einschalten",
    "Take out the trash" : "den Müll rausbringen",
    "Hang up the laundry" : "Die Wäsche aufhängen",
    "Wash the dishes" : "Das Geschirr spülen",
    "Clean the windows" : "Die Fenster putzen",
    "Cook/Boil (verb)" : "Kochen",
    "Lay the table" : "Den Tisch decken",
    "Do Homework" : "Machen Hausaufgaben",
    "Note/Memo (noun)" : "Die Notiz",
    "Finally/At last" : "Endlich",
    "Report (noun)" : "Der Bericht",
    "Backpack" : "Der Rucksack",
    "Reason/Bottom" : "Der Grund",
    "Married couple" : "Das Ehepaar",
    "Additionally" : "Dazu",
    "Garden" : "Der Garten",
    "Be glad/Rejoice" : "Freuen",
    "Genuine/Real" : "Echt",
    "Consider/Observe" : "Beachten",

}

Vocabulary_Kapitel_14 = {

    #Übungen
    "Certain/Definite" : "Bestimmt",
    "Earn" : "Verdienen",
    "Open/Inaugurate" : "Eröffnen",
    "Ship" : "Das Schiff",
    "Move/Shift" : "Bewegen",
    "Fall/Topple" : "Stürzen",
    "On the way/On the road" : "Unterwegs",
    "Movement/Motion" : "Die Bewegung",
    "Spell" : "Buchstabieren",


}

Vocabulary_Kapitel_15 = {

    "Win/Gain" : "Gewinnen",

}

from word import Word

Vocabulary_Nicos_Weg_A2_0 = [

    # Sprichst du Deutsch?
    Word("Pronounciation", "die Aussprache"),
    Word("Definitely, certainly", "bestimmt"),
    Word("That isn't enough", "das reicht nicht"),
    Word("Dialect", "der Dialekt,-e"),
    Word("I am interested (in)", "Es interessiert mich"),
    Word("Grammar", "die Grammatik"),
    Word("Greeting", "die Gruß,Grüße"),
    Word("Best regards", "Mit freundlichen Grüßen"),
    Word("I would like to know", "Ich möchte gerne wissen"),
    Word("King", "der König,-e"),
    Word("Queen", "die Königin,-nen"),
    Word("To take a course", "einen Kurs besuchen"),
    Word("To have a look, to check, to look up something", "etwas nach|sehen"),
    Word("To manage something", "etwas schaffen"),
    Word("Ship", "das Schiff,-e"),
    Word("Self, oneself", "selbst"),
    Word("Worry, concern", "die Sorge,-n"),
    Word("To correct, to improve", "etwas verbessern"),
    Word("To agree on something, to arrange something", "etwas vereinbaren"),
    Word("What about ...?, What's up with ...?", "was ist mit ...?"),
    Word("Funny", "witzig"),

    # Pläne machen
    Word("To be afraid", "angst haben"),
    Word("Work permit", "die Arbeitserlaubnis,-se"),
    Word("No way, on no account", "auf keinen Fall"),
    Word("Biology", "die Biologie"),
    Word("Success", "der Erfolg,-e"),
    Word("Successful", "erfolgreich"),
    Word("To take an exam", "Examen machen"),
    Word("Company", "die Firma,Firmen"),
    Word("Law", "das Gesetz,-e"),
    Word("Integration", "die Integration"),
    Word("Intensive course", "der Intensivkurs,-e"),
    Word("Law (studying)", "Jura"),
    Word("Opinion", "die Meinung,-en"),
    Word("Migrant (male)", "der Migrant,-en"),
    Word("Migrant (female)", "die Migrantin,-nen"),
    Word("Even better", "noch besser"),
    Word("Internship, practical training", "das Praktikum,Praktika"),
    Word("Process, procedure", "der Prozess,-e"),
    Word("Studies", "das Studium,Studien"),
    Word("Goal, target", "das Ziel,-e"),
    Word("Plans for the future", "der Zukunftsplan,Zukunftspläne"),
    Word("Future", "die Zukunft,Zukünfte"),

    # Angekommen
    Word("Beginning", "der Anfang,Anfänge"),
    Word("Telephone Call", "der Anruf,-e"),
    Word("To have/take a look at something", "sich etwas an|sehen"),
    Word("To look after something/someone", "auf etwas/jemanden auf|passen"),
    Word("Au-pair (male)", "der Au-Pair-Junge,-n"),
    Word("Au-pair (female)", "das Au-Pair-Mädchen,-"),
    Word("That", "dass"),
    Word("Foreign, Strange, Unfamiliar", "fremd"),
    Word("At most, Highest", "höchstens"),
    Word("Information", "die Information,-en"),
    Word("Including", "inklusive"),
    Word("At least, Minimum", "mindestens"),
    Word("To pack something", "etwas packen"),
    Word("Situation", "die Situation,-en"),
    Word("Allowance, Pocket money", "das Taschengeld"),
    Word("Turkey", "die Türkei"),
    Word("Accommodation, Board", "die Unterkunft,Unterkünfte"),
    Word("To earn something", "etwas verdienen"),
    Word("To leave something/someone", "etwas/jemanden verlassen"),
    Word("Food, Board, Meals", "die Verpflegung,-en"),
    Word("Why", "warum"),
    Word("Because", "weil"),
    Word("To cry", "weinen"),
    Word("Why", "weshalb"),
    Word("Why", "wieso"),
    Word("Home", "das Zuhause"),
    Word("It is true that..., but", "zwar ..., aber"),

    # Lebenslinien
    Word("High-School Graduation", "das Abitur"),
    Word("Beginner (male)", "der Anfänger,-"),
    Word("Autor (male)", "der Autor,-en"),
    Word("Back then", "damals"),
    Word("To be released", "erscheinen"),
    Word("About, Roughly", "etwa"),
    Word("To flee from something", "vor etwas fliehen"),
    Word("Advanced student (male)", "der Fortgeschrittene,-n"),
    Word("Complete/ly, Entire/ly", "ganz"),
    Word("To belong to someone", "jemandem gehören"),
    Word("Story", "die Geschichte,-n"),
    Word("Still", "immer noch"),
    Word("To have interest in", "interesse (an etwas) haben"),
    Word("Knowledge", "die Kenntnis,-se"),
    Word("War", "der Krieg,-e"),
    Word("Artist (male)", "der Künstler,-"),
    Word("Painter (male)", "der Maler,-"),
    Word("Level, Standard", "das Niveau,-s"),
    Word("Postcard", "die Postkarte,-n"),
    Word("Prize", "der Preis,-e"),
    Word("Actor (male)", "der Schauspieler,-"),
    Word("Switzerland", "die Schweiz"),
    Word("Since", "seit"),
    Word("To die", "sterben"),
    Word("From the beginning", "von Anfang an"),
    Word("Ago", "vor"),
    Word("World", "die Welt"),
    Word("To return, Come back", "zurück|kommen"),

]

Vocabulary_Nicos_Weg_A2_1 = [

    # Geld ist für mich...
    Word("Than", "als"),
    Word("To register", "sich an|melden"),
    Word("To spend", "etwas aus|geben"),
    Word("Foreigner (male)", "der Ausländer,-"),
    Word("Foreigner (female)", "die Ausländerin,-nen"),
    Word("Basic bank account", "das Basiskonto,Basiskonten"),
    Word("Certificate", "die Bescheinigung,-en"),
    Word("Thankful", "dankbar"),
    Word("Hence, that is why", "deshalb"),
    Word("Relieved", "erleichtert"),
    Word("To open something (often for the first time)", "etwas eröffnen"),
    Word("EU citizen (male)", "der EU-Bürger,-"),
    Word("To be pleased, to be glad", "sich freuen"),
    Word("Thrifty, miserly", "geizig"),
    Word("Banknote", "der Geldschein,-e"),
    Word("Conversation", "das Gespräch,-e"),
    Word("Current account, checking account", "das Girokonto,Girokonten"),
    Word("Account", "das Konto,Konten"),
    Word("To be able to afford something", "sich etwas leisten können"),
    Word("Coin", "die Münze,-n"),
    Word("Mad/angry at someone", "auf jemanden sauer"),
    Word("Certainly, surely", "sicher"),
    Word("To save (some money)", "(etwas) sparen"),
    Word("Savings account", "das Sparkonto,Sparkonten"),
    Word("Electricity", "der Strom"),
    Word("Really?", "wirklich?"),
    Word("Angry, furious", "wütend"),
    Word("To save, to set aside", "etwas zurück|legen"),

    # Mein Bankkonto
    Word("To withdraw something", "etwas ab|heben"),
    Word("Registration", "die Anmeldung,-en"),
    Word("In any case, definitely", "auf jeden Fall"),
    Word("To fill out something (i.e., a form)", "etwas aus|füllen"),
    Word("Bank clerk (male)", "der Bankangestellte,-n"),
    Word("Bank clerk (female)", "die Bankangestellte,-n"),
    Word("ATM, cash machine", "der Geldautomat,-en"),
    Word("Bank thief (male)", "der Bankräuber,-"),
    Word("Bank thief (female)", "die Bankräuberin,-nen"),
    Word("Cash", "das Bargeld"),
    Word("Income", "das Einkommen,-"),
    Word("Secure income", "das feste Einkommen"),
    Word("Marital status", "der Familienstand"),
    Word("Form", "das Formular,-e"),
    Word("Fee", "die Gebühr,-en"),
    Word("Birthdate", "das Geburtsdatum,Geburtsdaten"),
    Word("Place of birth", "der Geburtsort,-e"),
    Word("PIN number", "die Geheimzahl,-en"),
    Word("Gender", "das Geschlecht,-er"),
    Word("Debit card", "die Girocard,-s"),
    Word("Loan, credit", "der Kredit,-e"),
    Word("Credit card", "die Kreditkarte,-n"),
    Word("To lend somebody something", "jemandem etwas leihen"),
    Word("To mean something/someone", "etwas/jemanden meinen"),
    Word("What do you mean by that?", "was meinst du damit?"),
    Word("To inquire", "nach|fragen"),
    Word("Nationality", "die Nationalität,-en"),
    Word("By, via", "per"),
    Word("Via post", "per Post"),
    Word("PIN", "die PIN-Nummer,-n"),
    Word("To overdraw (money)", "etwas überziehen"),
    Word("Superior (male)", "der Vorgesetzte,-n"),
    Word("Superior (female)", "die Vorgesetzte,-n"),

    # Rechnungen
    Word("To debit or to charge something", "etwas ab|buchen"),
    Word("To be deducted", "ab|gehen"),
    Word("To pay attention to something/somebody", "auf etwas/jemanden achten"),
    Word("To leave something on, to leave something running", "etwas an|lassen"),
    Word("Kind, type, form", "die Art,-en"),
    Word("To turn something off", "etwas aus|schalten"),
    Word("To attest something", "etwas bescheinigen"),
    Word("Amount", "der Betrag,Beträge"),
    Word("Standing order", "der Dauerauftrag,Daueraufträge"),
    Word("To enter something (like a password)", "etwas ein|geben"),
    Word("To enter or apply", "ein|gehen"),
    Word("To set something up (physical/technical)", "etwas ein|richten"),
    Word("To deposit something", "etwas ein|zahlen"),
    Word("Recipient (male)", "der Empfänger,-"),
    Word("To remind someone of something", "jemanden an etwas erinnern"),
    Word("Reminder", "die Erinnerung,-en"),
    Word("Gas", "das Gas"),
    Word("To be in the minus, in the red", "im Minus sein"),
    Word("To be in the plus, in the black", "im Plus sein"),
    Word("Account holder (male)", "der Kontoinhaber,-"),
    Word("Account balance", "der Kontostand,Kontostände"),
    Word("To take out a loan, to borrow (loan, money)", "einen Kredit auf|nehmen"),
    Word("To look after, take care of something/somebody", "sich um etwas/jemanden kümmern"),
    Word("Direct debit", "die Lastschrift,-en"),
    Word("Light", "das Licht,-er"),
    Word("Warning, overdue notice", "die Mahnung,-en"),
    Word("Receipt, bill", "die Quittung,-en"),

    # Am Bankautomaten
    Word("Cancellation, demolition, abortion", "der Abbruch,Abbrüche"),
    Word("To print out something", "etwas aus|drucken"),
    Word("To choose something/somebody", "etwas/jemanden aus|wählen"),
    Word("Payout, withdrawal", "die Auszahlung,-en"),
    Word("Vending machine", "der Automat,-en"),
    Word("Confirmation", "die Bestätigung,-en"),
    Word("Data (information)", "die Daten"),
    Word("To print (something)", "(etwas) drucken"),
    Word("To press something", "auf etwas drücken"),
    Word("To enter something (like a PIN)", "etwas ein|geben"),
    Word("Deposit, (in)payment", "die Einzahlung,-en"),
    Word("An error message", "die Fehlermeldung,-en"),
    Word("To come out", "heraus|kommen"),
    Word("Account statement", "der Kontoauszug,Kontoauszüge"),
    Word("Correction", "die Korrektur,-en"),
    Word("Possible", "möglich"),
    Word("PIN", "die PIN,-s"),
    Word("Semester(s)", "das Semester,-"),
    Word("To stick inside", "stecken"),
    Word("Button, key (on a keyboard)", "die Taste,-n"),
    Word("To click on, to tap on", "auf etwas tippen"),
    Word("Lastly, finally", "zuletzt"),

]

Vocabulary_Nicos_Weg_A2_2 = [

    # Familiengeschichten
    Word("To leave, to dip out, to scram", "ab|hauen", "Images/Vocabulary_Nicos_Weg_A2_2/abhauen"),
    Word("Besides", "außerdem"),
    Word("At", "bei"),
    Word("Grown-up, mature", "erwachsen", "Images/Vocabulary_Nicos_Weg_A2_2/erwachsen"),
    Word("With", "mit"),
    Word("To push something, to move something", "etwas schieben", "Images/Vocabulary_Nicos_Weg_A2_2/schieben"),
    Word("Single person", "der Single,-s"),
    Word("To play with somebody", "mit jemandem spielen"),
    Word("Strict", "streng", "Images/Vocabulary_Nicos_Weg_A2_2/streng"),
    Word("To forget something/someone", "etwas/jemanden vergessen"),
    Word("To listen to someone", "jemandem zu|hören", "Images/Vocabulary_Nicos_Weg_A2_2/zuhören"),

    # Personen beschreiben
    Word("First, in the beginning", "am Anfang"),
    Word("Beard", "der Bart,Bärte"),
    Word("To describe something/somebody", "etwas/jemanden beschreiben", "Images/Vocabulary_Nicos_Weg_A2_2/beschreiben"),
    Word("Blonde", "blond", "Images/Vocabulary_Nicos_Weg_A2_2/blond"),
    Word("All the way, completely", "ganz"),
    Word("Heart", "das Herz,-en", "Images/Vocabulary_Nicos_Weg_A2_2/herz"),
    Word("To smile", "lächeln", "Images/Vocabulary_Nicos_Weg_A2_2/lächeln"),
    Word("Song", "das Lied,-er"),
    Word("Note", "die Notiz,-en", "Images/Vocabulary_Nicos_Weg_A2_2/notiz"),
    Word("Open, open-minded", "offen"),
    Word("Tolerant, open-minded", "tolerant"),
    Word("To translate something", "etwas übersetzen", "Images/Vocabulary_Nicos_Weg_A2_2/übersetzen"),
    Word("Preparation", "die Vorbereitung,-en"),
    Word("Repetition", "die Wiederholung,-en"),

    # Generationen
    Word("Geriatric nurse (male)", "der Altenpfleger,-", "Images/Vocabulary_Nicos_Weg_A2_2/altenpfleger"),
    Word("Geriatric nurse (female)", "die Altenpflegerin,-nen"),
    Word("Outpatient", "ambulant"),
    Word("To accompany something/someone, to support sth/sb", "etwas/jemanden begleiten", "Images/Vocabulary_Nicos_Weg_A2_2/begleiten"),
    Word("Complaints, symptoms", "die Beschwerden", "Images/Vocabulary_Nicos_Weg_A2_2/beschwerden"),
    Word("Refugee home", "das Flüchtlingsheim,-e"),
    Word("Walking stick", "der Gehstock,Gehstöcke", "Images/Vocabulary_Nicos_Weg_A2_2/gehstock"),
    Word("Hearing aid", "das Hörgerät,-e", "Images/Vocabulary_Nicos_Weg_A2_2/hörgerät"),

    # Alten- und Pflegeheim
    Word("Retirement home", "das Altenheim,-e", "Images/Vocabulary_Nicos_Weg_A2_2/altenheim"),
    Word("Excellent", "ausgezeichnet", "Images/Vocabulary_Nicos_Weg_A2_2/ausgezeichnet"),
    Word("That's why, for that reason", "deswegen"),
    Word("Lonely", "einsam", "Images/Vocabulary_Nicos_Weg_A2_2/einsam"),
    Word("Energy, power", "die Energie,-n"),
    Word("Reason", "der Grund,Gründe"),
    Word("Mobile, portable", "mobil"),
    Word("Retiree, pensioner (male)", "der Rentner,-", "Images/Vocabulary_Nicos_Weg_A2_2/rentner"),
    Word("Retiree, pensioner (female)", "die Rentnerin,-nen"),
    Word("Weak", "schwach"),
    Word("Oh, Pardon!", "Oh, Verzeihung!"),

]

Vocabulary_Nicos_Weg_A2_3 = [

    # Wohngemeinschaft
    Word("Iron (for clothing)", "das Bügeleisen,-", "Images/Vocabulary_Nicos_Weg_A2_3/bügeleisen"),
    Word("To iron (something)", "(etwas) bügeln", "Images/Vocabulary_Nicos_Weg_A2_3/bügeln"),
    Word("Brush, scrubber", "die Bürste,-n", "Images/Vocabulary_Nicos_Weg_A2_3/bürste"),
    Word("Chaos", "das Chaos"),
    Word("To move in", "ein|ziehen", "Images/Vocabulary_Nicos_Weg_A2_3/einziehen"),
    Word("To sweep (something)", "(etwas) fegen", "Images/Vocabulary_Nicos_Weg_A2_3/fegen"),
    Word("Rag, cloth", "der Lappen,-"),
    Word("Empty", "leer"),
    Word("Waste bin", "der Mülleimer,-", "Images/Vocabulary_Nicos_Weg_A2_3/mülleimer"),
    Word("Garbage can", "der Mülltonne,-n", "Images/Vocabulary_Nicos_Weg_A2_3/mülltonne"),
    Word("Deposit bottle", "die Pfandflasche,-n", "Images/Vocabulary_Nicos_Weg_A2_3/pfandflasche"),
    Word("Plant", "die Pflanze,-n", "Images/Vocabulary_Nicos_Weg_A2_3/pflanze"),
    Word("To take sth/sb out(side)", "etwas/jemanden raus|bringen"),
    Word("To stay calm/quiet", "ruhig bleiben"),
    Word("To clean up", "sauber machen", "Images/Vocabulary_Nicos_Weg_A2_3/sauber_machen"),
    Word("To vacuum", "saugen", "Images/Vocabulary_Nicos_Weg_A2_3/saugen"),
    Word("Sponge", "der Schwamm,Schwämme", "Images/Vocabulary_Nicos_Weg_A2_3/schwamm"),
    Word("Self, yourself", "selber/selbst"),
    Word("Dust", "der Staub", "Images/Vocabulary_Nicos_Weg_A2_3/staub"),
    Word("To dust, to wipe away dust", "Staub wischen"),
    Word("To dry sth", "etwas trocknen"),
    Word("Full, filled", "voll"),
    Word("To take sth/sb away", "etwas/jemanden weg|bringen"),
    Word("To dust, to wipe, to mop", "wischen", "Images/Vocabulary_Nicos_Weg_A2_3/wischen"),

    #Nachbarschaft
    

]

Grammatik_Aktiv = [

    # Reflexive (und reziproke) Verben
    Word("To comb (oneself)", "sich kämmen"),
    Word("To get dressed", "sich an|ziehen"),
    Word("To wash (oneself)", "sich waschen"),
    Word("To undress (oneself)", "sich aus|ziehen"),
    Word("To injure (oneself)", "sich verletzen"),
    Word("To introduce (oneself)", "sich vor|stellen"),
    Word("To cut (oneself)", "sich schneiden"),
    Word("To entertain, chat (oneself)", "sich unterhalten"),
    Word("To get a doctor's note", "sich krankschreiben lassen"),
    Word("To remember/recall (oneself)", "sich erinnern an"),
    Word("To prepare (oneself)", "sich vor|bereiten"),
    Word("To dress up/make oneself look nice", "sich schick machen"),
    Word("To get lost (on foot)", "sich verlaufen"),
    Word("To argue/fight (about something)", "sich streiten (über etwas)"),
    Word("To apologize (to someone)", "sich entschuldigen (bei jemandem)"),
    Word("To fall in love (with somebody)", "sich verlieben (in jemanden)"),
    Word("To separate/split up (from somebody)", "sich trennen (von jemandem)"),
    Word("To enjoy oneself", "sich amüsieren"),

    # 51: Reflexivpronomen im Dativ
    Word("To comb one's (specific part)", "sich etwas kämmen"),
    Word("To put on (clothing)", "sich etwas an|ziehen"),
    Word("To wash one's (specific body part)", "sich etwas waschen"),
    Word("To take off (clothing)", "sich etwas aus|ziehen"),
    Word("To injure (specific body part)", "sich etwas verletzen"),
    Word("To buy something for oneself", "sich etwas kaufen"),
    Word("To wish oneself something", "sich etwas wünschen"),
    Word("To choose something for oneself", "sich etwas aus|suchen"),
    Word("To imagine something", "sich etwas vor|stellen"),
    Word("To plan something for oneself", "sich etwas vor|nehmen"),
    Word("To break, fracture one's (specific body part)", "sich etwas brechen"),
    Word("To worry about something", "sich Sorgen um etwas machen"),
    Word("To cut one's (specific body part)", "sich etwas schneiden"),
    Word("To have/get something made/done (for oneself)", "sich etwas machen lassen"),
    Word("To paint/polish one's (nails)", "sich die Nägel lackieren"),

    # Trennbare und untrennbare Verben
    Word("To buy something", "ein|kaufen"),
    Word("To call somebody", "an|rufen"),
    Word("To turn off (electronics), to arrange/agree on (an appointment)", "aus|machen"),
    Word("To invite somebody", "ein|laden"),
    Word("To tidy up, to clean up", "auf|räumen"),
    Word("To enter, get in, board", "ein|steigen"),
    Word("To get out, exit", "aus|steigen"),
    Word("To start/turn on (engines, cars)", "an|springen"),

]

