Vocabulary = {

    "A few/a couple of" : "Das Paar",
    "ATM" : "Der Geldautomat",
    "Actor" : "Der Schauspieler",
    "Admission ticket" : "Die Eintrittskarte",
    "Afternoon" : "Der Nachmittag",
    "Air" : "Die Luft",
    "Airplane" : "Das Flugzeug",
    "Airport" : "Der Flughafen",
    "Animal" : "Das Tier",
    "Apartment" : "Die Wohnung",
    "Arm" : "Der Arm",
    "Art Museum" : "Die Kunsthalle",
    "Artist" : "Der Künstler",
    "Aunt" : "Die Tante",
    "Baby" : "Das Baby",
    "Bag" : "Die Tasche",
    "Bag (2)" : "Die Tüte",
    "Bakery" : "Die Bäckerei",
    "Ballpoint pen" : "Der Kuli",
    "Banana" : "Die Banane",
    "Bathroom" : "Das Badezimmer",
    "Bear" : "Der Bär",
    "Beauty" : "Die Schönheit",
    "Bed" : "Das Bett",
    "Bee" : "Die Biene",
    "Beer" : "Das Bier",
    "Beetle" : "Der Käfer",
    "Bird" : "Der Vogel",
    "Blouse" : "Die Bluse",
    "Bottle" : "Die Flasche",
    "Boy" : "Der Junge",
    "Bread" : "Das Brot",
    "Breakfast" : "Das Frühstück",
    "Brightness" : "Die Helligkeit",
    "Brother" : "Der Bruder",
    "Butcher" : "Der Metzger",
    "Button" : "Der Knopf",
    "Car" : "Der Wagen",
    "Carpet" : "Der Teppich",
    "Cash register" : "Die Kasse",
    "Cat" : "Die Katze",
    "Cellphone" : "Das Handy",
    "Chair" : "Der Stuhl",
    "Chancellor" : "Der Kanzler",
    "Check" : "Die Rechnung",
    "Cheese" : "Der Käse",
    "Child" : "Das Kind",
    "Chocolate" : "Die Schokolade",
    "Cinema" : "Das Kino",
    "City" : "Die Stadt",
    "Class/Course" : "Der Kurs",
    "Clock" : "Die Uhr",
    "Clothes" : "Die Kleidung",
    "Clown" : "Der Clown",
    "Coat" : "Der Mantel",
    "Coffee" : "Der Kaffee",
    "Computer" : "Der Computer",
    "Concert" : "Das Konzert",
    "Corner" : "Die Ecke",
    "Cosmetics" : "Die Kosmetiks",
    "Cost" : "Die Kosten",
    "Cow" : "Die Kuh",
    "Cup" : "Die Tasse",



}

"""
    "Vegetarian" : "Vegetarier",
    "Chicken" : "Hähnchen",
    "French fries" : "Pommes",
    "Couch" : "Couch",
    "Bookcase" : "Das Bücherregal",
    "Ugly" : "Hässlich",
    "Bedroom" : "Das Schlafzimmer",
    "Comfortable" : "Bequem",
    "Feather" : "Feder",
    "Furniture" : "Möbel",
    "Empty" : "Leer",
    "Dinner" : "Abendessen",
    "Kitchen" : "Küche",
    "Fantastic" : "Fantastisch",
    "Closet" : "Der Schrank",
    "Alone" : "Allein",
    "Chess" : "Schach",
    "Different" : "Verschieden",
    "Fantastic" : "Fantastisch",
    "Tuesday" : "Der Dienstag",
    "Job interview" : "Jobinterview",
    "Size" : "Grösse",
    "Toilet" : "Toilet",
    "Excited" : "Aufgeregt",
    "Suit jacket" : "Das Sakko",
    "Idea" : "Idee",
    "Fetch" : "Holen",
    "Watch" : "Schauen", 
    "T-shirt" : "T-shirt",
    "Stylish" : "Schick",
    "Elevator" : "Aufzug",
    "Wednesday" : "Der Mittwoch",
    "Alone" : "Allein",
    "Reservation" : "Die Reservierung",
    "Birthday" : "Der Geburtstag"
    "Meet" : "Treffen",
    "Travel center" : "Reisezentrum",
    "Pay (verb)" : "Zahlen", 
    "Credit card" : "Die Kreditkarte",
    "Cancel" : "Stornieren",
    "Track (train)" : "Das Gleis",
    "Seat" : "Der Sitz",
    "Back (on the back) : "Hinten",
    "Departure" : "Die Abfahrt",
    "Minute" : "Die Minute",
    

"""

"""
# learning genders

    "A few/a couple of" : "Das Paar",
    "ATM" : "Der Geldautomat",
    "Actor" : "Der Schauspieler",
    "Admission ticket" : "Die Eintrittskarte",
    "Afternoon" : "Der Nachmittag",
    "Air" : "Die Luft",
    "Airplane" : "Das Flugzeug",
    "Airport" : "Der Flughafen",
    "Animal" : "Das Tier",
    "Apartment" : "Die Wohnung",
    "Arm" : "Der Arm",
    "Art Museum" : "Die Kunsthalle",
    "Artist" : "Der Künstler",
    "Aunt" : "Die Tante",
    "Baby" : "Das Baby",
    "Bag" : "Die Tasche",
    "Bag (2)" : "Die Tüte",
    "Bakery" : "Die Bäckerei",
    "Ballpoint pen" : "Der Kuli",
    "Banana" : "Die Banane",
    "Bathroom" : "Das Badezimmer",
    "Bear" : "Der Bär",
    "Beauty" : "Die Schönheit",
    "Bed" : "Das Bett",
    "Bee" : "Die Biene",
    "Beer" : "Das Bier",
    "Beetle" : "Der Käfer",
    "Bird" : "Der Vogel",
    "Blouse" : "Die Bluse",
    "Bottle" : "Die Flasche",
    "Boy" : "Der Junge",
    "Bread" : "Das Brot",
    "Breakfast" : "Das Frühstück",
    "Brightness" : "Die Helligkeit",
    "Brother" : "Der Bruder",
    "Butcher" : "Der Metzger",
    "Button" : "Der Knopf",
    "Car" : "Der Wagen",
    "Carpet" : "Der Teppich",
    "Cash register" : "Die Kasse",
    "Cat" : "Die Katze",
    "Cellphone" : "Das Handy",
    "Chair" : "Der Stuhl",
    "Chancellor" : "Der Kanzler",
    "Check" : "Die Rechnung",
    "Cheese" : "Der Käse",
    "Child" : "Das Kind",
    "Chocolate" : "Die Schokolade",
    "Cinema" : "Das Kino",
    "City" : "Die Stadt",
    "Class/Course" : "Der Kurs",
    "Clock" : "Die Uhr",
    "Clothes" : "Die Kleidung",
    "Clown" : "Der Clown",
    "Coat" : "Der Mantel",
    "Coffee" : "Der Kaffee",
    "Computer" : "Der Computer",
    "Concert" : "Das Konzert",
    "Corner" : "Die Ecke",
    "Cosmetics" : "Die Kosmetiks",
    "Cost" : "Die Kosten",
    "Cow" : "Die Kuh",
    "Cup" : "Die Tasse",

    #neue nommen! 
    "Dance (noun)" : "Der Tanz",
    "Date" : "Das Date",
    "Daughter" : "Die Tochter",
    "Dentist" : "Der Zahnarzt",
    "Department store" : "Das Kaufhaus",
    "Desk" : "Der Schreibtisch",
    "Dictionary" : "Das Wörterbuch",
    "Doctor" : "Der Arzt",
    "Dog" : "Der Hund",
    "Door" : "Die Tür",
    "Dress" : "Das Kleid",
    "Duck" : "Die Ente",
    "Earth" : "Die Erde",
    "Egg" : "Das Ei",
    "Elephant" : "Der Elefant",
    "Exam" : "Das Examen",
    "Fall/Autumn (2)" : "Der Herbst",
    "Father" : "Der Vater",
    "Fear" : "Die Angst",
    "Fire" : "Das Feuer",
    "Fish" : "Der Fisch",
    "Floor" : "Der Boden",
    "Flower" : "Die Blume",
    "Food" : "Das Essen",
    "Food/Dish" : "Die Speise",
    "Football game" : "Das Fussballspiel",
    "Foreigner" : "Der Ausländer",
    "Friend" : "Der Freund",
    "Friend/Girlfriend" : "Die Freundin",
    "Fruit" : "Das Obst",
    "Fun" : "Der Spass",
    "Game" : "Das Spiel",
    "Gift" : "Das Geschenk",
    "Girl" : "Das Mädchen",
    "Glass" : "Das Glas",
    "Grandfather" : "Der Grossvater",
    "Grandmother" : "Die Grossmutter",
    "Guitar" : "Die Gitarre",
    "Hair" : "Das Haar",
    "Hand" : "Die Hand",
    "Hat" : "Der Hut",
"""
# hacer seccion 2, unit 9